#!/bin/sh

if [ $# -ne 2 ]; then
  echo "Usage: $0 ssh-profile salt-master"
  exit 1
fi

ssh $1 "sudo pkg upgrade -y"
ssh $1 "sudo pkg install -y py27-salt"
ssh $1 "sudo sysrc salt_minion_enable=YES"
ssh $1 "sudo cp /usr/local/etc/salt/minion.sample /usr/local/etc/salt/minion"
ssh $1 "sudo sed -i '' 's/#master: salt/master: $2/' /usr/local/etc/salt/minion"
ssh $1 "sudo service salt_minion start"
